// constants/apis.ts
export const BASE_URL = "https://data.gov.il/api/3/action/datastore_search?resource_id=";
export const GOV_APIS = {
  VEHICLE_QUANTITIES_DATABASE_BY_MANUFACTURER_MODEL_AND_YEAR_OF_MANUFACTURE: {
    id: "5e87a7a1-2f6f-41c1-8aec-7216d52a6cf6",
    description:
      "This database contains official information on the quantities of active and inactive vehicles by private vehicle models from 1996 onwards and commercial vehicle models from 1998 onwards, including year of manufacture and model code.",
    example_result: {
      _id: 1,
      sug_degem: "P",
      tozeret_cd: 19,
      tozeret_nm: "אאודי",
      tozeret_eretz_nm: "גרמניה",
      tozar: "אאודי",
      degem_cd: 2681,
      degem_nm: "8K201H",
      shnat_yitzur: 2010,
      mispar_rechavim_pailim: 61,
      mispar_rechavim_le_pailim: 39,
      kinuy_mishari: "A4",
    },
    notes: [
      "Use this API to get the number of vehicles of a specific model and year.",
      "when querying, use three fields degem_nm and shnat_yitzur and degem_cd",
    ],
  },
  VEHICLE_MANUFACTURERS_AND_MODELS_WLTP: {
    id: "142afde2-6228-49f9-8a29-9b6c3a0cbe40",
    description:
      "Vehicle manufacturers and models with WLTP data, which is a global standard for measuring fuel consumption and emissions.",
    example_result: {
      _id: 1,
      sug_degem: "M",
      tozeret_cd: 5,
      tozeret_nm: "צ'אנג יאנג סין",
      tozeret_eretz_nm: "סין",
      tozar: "צ'אנג יאנג",
      degem_cd: 179,
      degem_nm: "4MN0N2",
      shnat_yitzur: 2021,
      kvuzat_agra_cd: 7,
      nefah_manoa: 2967,
      mishkal_kolel: 2900,
      gova: 0,
      hanaa_cd: null,
      hanaa_nm: "לא ידוע קוד ",
      mazgan_ind: 1,
      abs_ind: 1,
      kariot_avir_source: "6",
      mispar_kariot_avir: 6,
      hege_koah_ind: 1,
      automatic_ind: 1,
      halonot_hashmal_source: "4",
      mispar_halonot_hashmal: 4,
      halon_bagg_ind: 1,
      galgaley_sagsoget_kala_ind: 1,
      argaz_ind: 0,
      merkav: "פנאי-שטח",
      ramat_gimur: "COMFORT",
      delek_cd: 2,
      delek_nm: "דיזל",
      mispar_dlatot: 5,
      koah_sus: 286,
      mispar_moshavim: 5,
      bakarat_yatzivut_ind: 1,
      kosher_grira_im_blamim: 3500,
      kosher_grira_bli_blamim: 750,
      sug_tkina_cd: 1,
      sug_tkina_nm: "אירופאית",
      sug_mamir_cd: 2,
      sug_mamir_nm: "לוכד חלקיקים",
      technologiat_hanaa_cd: null,
      technologiat_hanaa_nm: "הנעה רגילה",
      kamut_CO2: null,
      kamut_NOX: null,
      kamut_PM10: null,
      kamut_HC: null,
      kamut_HC_NOX: null,
      kamut_CO: null,
      kamut_CO2_city: null,
      kamut_NOX_city: null,
      kamut_PM10_city: null,
      kamut_HC_city: null,
      kamut_CO_city: null,
      kamut_CO2_hway: null,
      kamut_NOX_hway: null,
      kamut_PM10_hway: null,
      kamut_HC_hway: null,
      kamut_CO_hway: null,
      madad_yarok: 327,
      kvutzat_zihum: 15,
      bakarat_stiya_menativ_ind: 1,
      bakarat_stiya_menativ_makor_hatkana: "יצרן",
      nitur_merhak_milfanim_ind: 1,
      nitur_merhak_milfanim_makor_hatkana: "יצרן",
      zihuy_beshetah_nistar_ind: 1,
      bakarat_shyut_adaptivit_ind: 1,
      zihuy_holchey_regel_ind: 1,
      zihuy_holchey_regel_makor_hatkana: "יצרן",
      maarechet_ezer_labalam_ind: 1,
      matzlemat_reverse_ind: 1,
      hayshaney_lahatz_avir_batzmigim_ind: 1,
      hayshaney_hagorot_ind: 0,
      nikud_betihut: 5.0,
      ramat_eivzur_betihuty: 5,
      teura_automatit_benesiya_kadima_ind: 1,
      shlita_automatit_beorot_gvohim_ind: 1,
      shlita_automatit_beorot_gvohim_makor_hatkana: "יצרן",
      zihuy_matzav_hitkarvut_mesukenet_ind: 1,
      zihuy_tamrurey_tnua_ind: 0,
      zihuy_rechev_do_galgali: 1,
      zihuy_tamrurey_tnua_makor_hatkana: "",
      CO2_WLTP: 221,
      HC_WLTP: 31.4,
      PM_WLTP: 0.37,
      NOX_WLTP: 17.2,
      CO_WLTP: 92.9,
      CO2_WLTP_NEDC: null,
      bakarat_stiya_activ_s: 1,
      blima_otomatit_nesia_leahor: 1,
      bakarat_mehirut_isa: 0,
      blimat_hirum_lifnei_holhei_regel_ofanaim: 1,
      hitnagshut_cad_shetah_met: 0,
      alco_lock: 0,
      dg_metach_solela: null,
      kinuy_mishari: "Q8",
    },
    notes: [
      "Use this API to get detailed information about vehicle models that comply with WLTP standards.",
      "when querying, use three fields degem_nm and shnat_yitzur and degem_cd",
    ],
  },

  PERSONAL_IMPORTED_VEHICLES: {
    id: "03adc637-b6fe-402b-9937-7c3d3afc9140",
    description: "Personal imported vehicles (רכב פרטי מיובא)",
    example_result: {
      _id: 1,
      mispar_rechev: 4681815,
      shilda: "WDB2100611A948257",
      tozeret_cd: 593,
      tozeret_nm: "מרצדס בנץ גרמנ",
      sug_rechev_cd: 112,
      sug_rechev_nm: "פרטי נוסעים",
      degem_nm: "E240",
      mishkal_kolel: 0,
      shnat_yitzur: 2000,
      nefach_manoa: 2398,
      tozeret_eretz_nm: "גרמניה",
      degem_manoa: "OM112",
      mivchan_acharon_dt: "2025-05-03",
      tokef_dt: "2025-10-03",
      sug_yevu: "יבוא אישי-משומש",
      moed_aliya_lakvish: null,
      sug_delek_nm: "בנזין",
    },
  },
  VEICHALES_ELEGIBLE_FOR_DISCOUNT: {
    id: "83bfb278-7be1-4dab-ae2d-40125a923da1",
    description: "Vehicles eligible for discount (רכבים זכאים להנחה)",
    example_result: {
      _id: 1,
      mispar_rechev: 4150164,
      updated_dt: "2025-08-25 04:02:41.660000000",
    },
  },
  LICENSE_PLATE_NUMBERS_OF_PRIVATE_AND_COMMERCIAL_VEHICLES: {
    id: "053cea08-09bc-40ec-8f7a-156f0677aff3",
    description:
      "Licensing numbers of private and commercial vehicles (מספרי רישוי של רכבים פרטיים ומסחריים)",
    example_result: {
      _id: 1,
      mispar_rechev: 1000068,
      tozeret_cd: 683,
      sug_degem: "P",
      tozeret_nm: "סוזוקי-יפן",
      degem_cd: 292,
      degem_nm: "JTD54V",
      ramat_gimur: "JLX",
      ramat_eivzur_betihuty: null,
      kvutzat_zihum: 15,
      shnat_yitzur: 2008,
      degem_manoa: "J20A",
      mivchan_acharon_dt: "2024-11-29",
      tokef_dt: "2025-11-29",
      baalut: "פרטי",
      misgeret: "JSAJTD54V90300319",
      tzeva_cd: 80,
      tzeva_rechev: "שנהב לבן",
      zmig_kidmi: "225/70R16",
      zmig_ahori: "225/70R16",
      sug_delek_nm: "בנזין",
      horaat_rishum: null,
      moed_aliya_lakvish: "2008-11",
      kinuy_mishari: "GRAND VITARA",
    },
    notes: [
      "License plate numbers of private and commercial vehicles",
      "Active private vehicles manufactured from 1996 and onwards",
      "Active commercial vehicles (up to 3,500 kg) manufactured from 1998 and onwards.",
    ],
  },
  LICENSE_PLATE_NUMBERS_OF_PRIVATE_AND_COMMERCIAL_VEHICLES_CONTINUED: {
    id: "0866573c-40cd-4ca8-91d2-9dd2d7a492e5",
    description:
      "This is a continuation of the previous database, providing additional records of licensing numbers for private and commercial vehicles.",
    example_result: {
      _id: 1,
      mispar_rechev: 1000310,
      tozeret_cd: 413,
      sug_degem: "M",
      degem_cd: 8511,
      kod_omes_tzmig_kidmi: 0,
      kod_omes_tzmig_ahori: 0,
      kod_mehirut_tzmig_kidmi: "",
      kod_mehirut_tzmig_ahori: "",
      grira_nm: "יש וו גרירה",
    },
    notes: [
      "please note that this is a continuation of the previous database, simply adding more fields.",
    ],
  },
  HISTORY_OF_PRIVATE_VEHICLES_2: {
    id: "bb2355dc-9ec7-4f06-9c3f-3344672171da",
    description:
      "The file contains the following data: license plate numbers, ownership dates, and type of ownership.The file does not include vehicles that had a previous license number.",
    example_result: {
      _id: 1,
      mispar_rechev: 14817,
      baalut_dt: 202202,
      baalut: "פרטי",
    },
    notes: [
      "Please note that this file does not include vehicles that had a previous license number.",
      "This contains historical ownership data for private vehicles. Data includes license plate numbers, ownership dates, and type of ownership.",
    ],
  },
  HISTORY_OF_PRIVATE_VEHICLES_1: {
    id: "56063a99-8a3e-4ff4-912e-5966c0279bad",
    description:
      "The databases present data about active private vehicles starting from the year 2017",
    example_result: {
      _id: 1,
      mispar_rechev: 44703802,
      mispar_manoa: "DLA 007865",
      kilometer_test_aharon: 121090,
      shinui_mivne_ind: 1,
      gapam_ind: 0,
      shnui_zeva_ind: 0,
      shinui_zmig_ind: 1,
      rishum_rishon_dt: "2021-02-03 00:00:00",
      mkoriut_nm: "החכר",
    },
    notes: [
      "The databases present data about active private vehicles starting from the year 2017 (Inclusive)",
      "Note that this is different from HISTORY_OF_PRIVATE_VEHICLES_2 which contains historical ownership data.",
      "However, this data will show the current ownership details along with the kilometer reading from the last test and any changes made to the vehicle's structure, color, or tires.",
    ],
  },
  VEHICLES_TAKEN_OFF_THE_ROAD_WITH_FINAL_CANCELLATION_STATUS_LATEST: {
    id: "851ecab1-0622-4dbe-a6c7-f950cf82abf9",
    description:
      "This dataset is about vehicles that are no longer allowed on the road at all.",
    example_result: {
      _id: 1,
      mispar_rechev: 4705339,
      tozeret_cd: 237,
      tozeret_nm: "פיג'ו סלובקיה",
      degem_cd: 28,
      degem_nm: "CCHNZT/S",
      sug_rechev_cd: 112,
      sug_rechev_nm: "פרטי נוסעים",
      moed_aliya_lakvish: 2016,
      bitul_dt: "2024-12-21 00:00:00",
      misgeret: "VF3CCHNZTGT135117",
      tozar_manoa: "פיגו סלובקיה",
      degem_manoa: "HN01",
      mispar_manoa: "10XVA10364002",
      mishkal_kolel: 1650,
      ramat_gimur: "ACTIVE PRO",
      ramat_eivzur_betihuty: 0,
      kvutzat_zihum: 13,
      shnat_yitzur: 2016,
      baalut: "פרטי",
      tzeva_rechev: "שנהב לבן",
      zmig_kidmi: "195/55R16",
      zmig_ahori: "195/55R16",
      sug_delek_nm: "בנזין",
      horaat_rishum: 160148,
      kinuy_mishari: "208",
    },
    notes: [
      "“ביטול סופי” (final cancellation status) means the car has been permanently deregistered (scrapped, exported, or otherwise not allowed back on the road).",
      "Covers all vehicles canceled since 2017",
      "Please for vehicles taken off the road before 2017, refer to the older dataset, there are two of them 2000-2009 and 2010-2016",
    ],
  },
  VEHICLES_TAKEN_OFF_THE_ROAD_WITH_FINAL_CANCELLATION_STATUS_2000_TO_2009_INCLUSIVE:
    {
      id: "ec8cbc34-72e1-4b69-9c48-22821ba0bd6c",
      description:
        "This dataset is about vehicles that are no longer allowed on the road at all.",
      example_result: {
        _id: 1,
        mispar_rechev: "04252235",
        tozeret_cd: "0778",
        tozeret_nm: "סיאט ספרד",
        degem_cd: "0180",
        degem_nm: "6K22K6",
        sug_rechev_cd: "112",
        sug_rechev_nm: "פרטי נוסעים",
        moed_aliya_lakvish: "",
        bitul_dt: "2009-06-30",
        misgeret: "VSSZZZ6KZ1R186114",
        tozar_manoa: "פולקסווגן",
        degem_manoa: "AGP",
        mispar_manoa: "AGP260206",
        mishkal_kolel: "0",
        ramat_gimur: "STELLA",
        ramat_eivzur_betihuty: "0",
        kvutzat_zihum: "0",
        shnat_yitzur: "2001",
        baalut: "פרטי",
        tzeva_rechev: "כסף מטלי",
        zmig_kidmi: "195.50.R15",
        zmig_ahori: "195.50.R15",
        sug_delek_nm: "דיזל",
        horaat_rishum: "0",
        kinuy_mishari: "CORDOBA",
      },
      notes: [
        "“ביטול סופי” (final cancellation status) means the car has been permanently deregistered (scrapped, exported, or otherwise not allowed back on the road).",
        "Covers all vehicles taken off the road between 2000 to 2009 inclusive, refer to this dataset",
      ],
    },
  VEHICLES_TAKEN_OFF_THE_ROAD_WITH_FINAL_CANCELLATION_STATUS_2010_TO_2016_INCLUSIVE:
    {
      id: "4e6b9724-4c1e-43f0-909a-154d4cc4e046",
      description:
        "This dataset is about vehicles that are no longer allowed on the road at all.",
      example_result: {
        _id: 1,
        mispar_rechev: "03602428",
        tozeret_cd: "0588",
        tozeret_nm: "מזדה יפן",
        degem_cd: "",
        degem_nm: "MPV-LV12J",
        sug_rechev_cd: "341",
        sug_rechev_nm: "מרכב אחוד",
        moed_aliya_lakvish: "",
        bitul_dt: "2015-02-01",
        misgeret: "JMZLV12J5-V0100553",
        tozar_manoa: "יפן מאזדה",
        degem_manoa: "JE",
        mispar_manoa: "625112",
        mishkal_kolel: "2340",
        ramat_gimur: "",
        ramat_eivzur_betihuty: "0",
        kvutzat_zihum: "0",
        shnat_yitzur: "1997",
        baalut: "פרטי",
        tzeva_rechev: " לא ידוע",
        zmig_kidmi: "P215/65R15",
        zmig_ahori: "",
        sug_delek_nm: "בנזין",
        horaat_rishum: "0",
        kinuy_mishari: "",
      },
      notes: [
        "“ביטול סופי” (final cancellation status) means the car has been permanently deregistered (scrapped, exported, or otherwise not allowed back on the road).",
        "Covers all vehicles taken off the road between 2010 to 2016 inclusive, refer to this dataset",
      ],
    },
  IMPORTERS_AND_PRICE_LISTS_OF_NEW_VEHICLES: {
    id: "39f455bf-6db0-4926-859d-017f34eacbcb",
    description:
      "This database presents the prices of new vehicle models by importer, as reported by the importer. (יבואנים ומחירון רכבים חדשים)",
    example_result: {
      _id: 1,
      semel_yevuan: 1,
      shem_yevuan: 'קרסו מוטורס בע"מ',
      sug_degem: "P",
      tozeret_cd: 928,
      tozeret_nm: "רנו צרפת",
      degem_cd: 1000,
      degem_nm: "C0635P R TWINGO EP",
      shnat_yitzur: 1996,
      mehir: 54950,
      kinuy_mishari: "טווינגו 2.1 YSAE",
    },
    notes: [
      "The prices of new vehicle models are updated whenever information is received from the importer",
      "The prices of continuing models (existing models that keep being sold) are updated once per year",
      "Each importer (יבואן) — like Toyota Israel, Hyundai Israel, etc. — submits official prices for the models they sell.",
      "The database collects those prices and publishes them.",
      "If a new model arrives → the price is updated as soon as the importer sends it.",
      "If a model is ongoing/continuing (not new, just the same model still sold) → its price is refreshed annually.",
    ],
  },
  LICENSE_PLATE_NUMBERS_OF_TWO_WHEELED_VEHICLES: {
    id: "bf9df4e2-d90d-4c0a-a400-19e15af8e95f",
    description:
      "This dataset is specifically for two-wheeled vehicles, such as motorcycles and scooters, unlike the previous ones which focused on cars (private or commercial) (מספרי רישוי של דו-גלגלי)",
    example_result: {
      _id: 1,
      mispar_rechev: 26361202,
      tozeret_cd: 847,
      tozeret_nm: "קוואסאקי יפן",
      tozeret_eretz_nm: "יפן",
      degem_nm: "ZR900B",
      shnat_yitzur: 2020,
      sug_delek_cd: 1,
      sug_delek_nm: "בנזין",
      mishkal_kolel: 0,
      mida_zmig_kidmi: "120/70ZR17",
      mida_zmig_ahori: "180/55ZR17",
      kod_omes_zmig_kidmi: 44,
      kod_omes_zmig_ahori: 64,
      kod_mehirut_zmig_kidmi: "V",
      kod_mehirut_zmig_ahori: "V",
      nefach_manoa: 948,
      hespek: 125.0,
      misgeret: "JKAZR900BBA034275",
      moed_aliya_lakvish: "2020-9",
      sug_rechev_EU_cd: "L3",
      sug_rechev_cd: 10,
      sug_rechev_nm: "אופנוע",
      mispar_manoa: "075607",
      horaat_rishum: 202067,
      baalut: "פרטי",
      mkoriut_nm: "",
      mispar_mekomot_leyd_nahag: 0,
      mispar_mekomot: 1,
    },
    notes: [
      "License plate numbers of two-wheeled vehicles",
      "Active two-wheeled vehicles manufactured from 2005 and onwards",
      "Covers only active vehicles that are currently registered.",
    ],
  },
  VEHICLES_WITH_A_DISABLED_PARKING_PERMIT: {
    id: "c8b9f9c8-4612-4068-934f-d4acd2e3c06e",
    description:
      "This database contains the license plate numbers of vehicles authorized to carry a disabled parking tag issued by the Ministry of Transport. (רכבים עם תג נכה)",
    example_result: {
      _id: 2,
      "MISPAR RECHEV": 70220,
      "TAARICH HAFAKAT TAG": 20250310,
      "SUG TAV": 1,
    },
    notes: [
      "note that veihcles without a disabled parking permit are not included in this dataset.",
    ],
  },
  VEHICLE_MANUFACTURER_NOTIFICATIONS_RECALL: {
    id: "2c33523f-87aa-44ec-a736-edbb0a82975e",
    description:"Vehicle manufacturer notifications (recall) - הודעות יצרן רכב (ריקול)",
    example_result: {
      _id: 1,
      RECALL_ID: 11020,
      TOZAR_CD: 1,
      TOZAR_TEUR: "TOYOTA",
      DEGEM: "AVENSIS",
      SHNAT_RECALL: 2011,
      BUILD_BEGIN_A: "2000-01-02 00:00:00",
      BUILD_END_A: "2008-12-31 00:00:00",
      SUG_RECALL: "תקלה סידרתית בטיחותית",
      SUG_TAKALA: "מנוע ומערכותיו",
      TEUR_TAKALA: "שסתום צינור דלק אוונסיס",
      OFEN_TIKUN: "החלפה",
      TKINA_EU: "M1",
      YEVUAN_TEUR: "יוניון מוטורס בעמ",
      TELEPHONE: "1-800-22-1514",
      WEBSITE: "WWW.TOYOTA.CO.IL/SERVICE-AND-ACCESSORIES/RECALL",
    },
    notes: [
      "To query, please use the field DEGEM "
    ],
  },
};
